
**************************************** CREATE **************************************
http://192.168.100.103/ibmetrodta/yii/web/index.php/detallecalibracion040301/create?records={"id_detalle_calibracion":null,"fk_id_peticion":1,"fk_id_campo_calibracion":1,"estado_detalle_calibracion":1,"objetivo_detalle_calibracion":"valor","descripcion_detalle_calibracion":"valor","norma_detalle_calibracion":"valor","equipo_calibrado_detalle_calibracion":"valor","tipo_servicio_detalle_calibracion":"valor","personal_autorizado_detalle_calibracion":"valor","rango_calibracion_detalle_calibracion":"valor","mejor_capacidad_medicion_detalle_calibracion":"valor","equipos_utilizados_detalle_calibracion":"valor","ad_estimacion_incertidumbre_detalle_calibracion":"valor","ad_patrones_referencia_detalle_calibracion":"valor","ad_manipulacion_patrones_referencia_detalle_calibracion":"valor","ad_fecha_ultima_calibracion_detalle_calibracion":"2015-01-01","ad_organismo_realizo_calibracion_detalle_calibracion":"valor","ad_certificado_calibracion_detalle_calibracion":"valor","ad_fecha_proxima_calibracion_detalle_calibracion":"2015-01-01","ad_declaracion_trazabilidad_detalle_calibracion":"valor","ad_criterio_aceptacion_detalle_calibracion":"valor","ad_comparaciones_interlaboratorios_detalle_calibracion":"valor","fecha_creacion_detalle_calibracion":"2015-01-01 00:00:00}&callback=Ext
**************************************** UPDATE **************************************
http://192.168.100.103/ibmetrodta/yii/web/index.php/detallecalibracion040301/update?records={"id_detalle_calibracion":1,"fk_id_peticion":1,"fk_id_campo_calibracion":1,"estado_detalle_calibracion":1,"objetivo_detalle_calibracion":"valorxx","descripcion_detalle_calibracion":"valorxx","norma_detalle_calibracion":"valorxx","equipo_calibrado_detalle_calibracion":"valorxx","tipo_servicio_detalle_calibracion":"valorxx","personal_autorizado_detalle_calibracion":"valorxx","rango_calibracion_detalle_calibracion":"valorxx","mejor_capacidad_medicion_detalle_calibracion":"valorxx","equipos_utilizados_detalle_calibracion":"valorxx","ad_estimacion_incertidumbre_detalle_calibracion":"valorxx","ad_patrones_referencia_detalle_calibracion":"valorxx","ad_manipulacion_patrones_referencia_detalle_calibracion":"valorxx","ad_fecha_ultima_calibracion_detalle_calibracion":"2015-01-01","ad_organismo_realizo_calibracion_detalle_calibracion":"valorxx","ad_certificado_calibracion_detalle_calibracion":"valorxx","ad_fecha_proxima_calibracion_detalle_calibracion":"2015-01-01","ad_declaracion_trazabilidad_detalle_calibracion":"valorxx","ad_criterio_aceptacion_detalle_calibracion":"valorxx","ad_comparaciones_interlaboratorios_detalle_calibracion":"valorxx","fecha_creacion_detalle_calibracion":"2015-01-01 00:00:00"}&callback=Ext
**************************************** DELETE **************************************
http://192.168.100.103/ibmetrodta/yii/web/index.php/detallecalibracion040301/delete?records={"id_detalle_calibracion":1}&callback=Ext
**************************************** READ ****************************************

http://192.168.100.103/ibmetrodta/yii/web/index.php/detallecalibracion040301/?start=0&limit=3&callback=Ext
**************************************************************************************
http://192.168.100.103/ibmetrodta/yii/web/index.php/detallecalibracion040301/?start=0&limit=3&filter=[{"property":"id_detalle_calibracion","value":1}]&callback=Ext
**************************************************************************************
http://192.168.100.103/ibmetrodta/yii/web/index.php/detallecalibracion040301/?start=0&limit=3&sort=[{"property":"id_detalle_calibracion","direction":"asc"}]&callback=Ext
**************************************************************************************
http://192.168.100.103/ibmetrodta/yii/web/index.php/detallecalibracion040301/?start=0&limit=3&filter=[{"property":"id_detalle_calibracion","value":1}]&sort=[{"property":"id_detalle_calibracion","direction":"asc"}]&callback=Ext

***************************************** QUERY *********************************************
http://192.168.100.103/ibmetrodta/yii/web/index.php/detallecalibracion040301/?start=0&limit=3&query=[{"id_detalle_calibracion":1}]&callback=Ext

