
**************************************** CREATE **************************************
http://192.168.100.103/ibmetrodta/yii/web/index.php/evaltecnica040801/create?records={"id_eval_tecnica":null,"fk_id_peticion":1,"area_ensayo_eval_tecnica":"valor","metodo_ensayo_eval_tecnica":"valor","lista_signatarios_eval_tecnica":"valor","supervision_personal_eval_tecnica":"valor","autorizacion_eval_tecnica":"valor","adecuacion_eval_tecnica":"valor","seguimiento_eval_tecnica":"valor","separacion_areas_eval_tecnica":"valor","control_acceso_eval_tecnica":"valor","orden_limpieza_eval_tecnica":"valor","uso_metodos_apropiados_eval_tecnica":"valor","confirmacion_metodos_eval_tecnica":"valor","instructivo_uso_eval_tecnica":"valor","validacion_desviaciones_eval_tecnica":"valor","estimacion_incertidumbre_eval_tecnica":"valor","verificacion_calculos_eval_tecnica":"valor","procedimientos_calibracion_eval_tecnica":"valor","trazabilidad_calibracion_eval_tecnica":"valor","disponibilidad_material_eval_tecnica":"valor","certificados_calibracion_eval_tecnica":"valor","plan_muestreo_eval_tecnica":"valor","registros_muestreo_eval_tecnica":"valor","tecnicas_estadisticas_eval_tecnica":"valor","procedimiento_muestras_eval_tecnica":"valor","sistema_identificacion_eval_tecnica":"valor","adecuacion_instalaciones_eval_tecnica":"valor","procedimiento_aseguramiento_eval_tecnica":"valor","uso_regular_material_eval_tecnica":"valor","participacion_intercomparaciones_eval_tecnica":"valor","repeticion_ensayos_eval_tecnica":"valor","correlacion_eval_tecnica":"valor","registro_aseguramiento_eval_tecnica":"valor","formatos_apropiados_eval_tecnica":"valor","cumple_requisitos_norma_eval_tecnica":"valor","documentacion_opiniones_eval_tecnica":"valor","seguridad_transmision_eval_tecnica":"valor","confidencialidad_eval_tecnica":"valor","criterios_insertidumbre_eval_tecnica":"valor","criterios_trazabilidad_eval_tecnica":"valor","numero_requisito_eval_tecnica":"valor","comentario_requisito_eval_tecnica":"valor","conclusion_eval_tecnica":"valor","fecha_inicio_eval_tecnica":"2015-01-01","fecha_fin_eval_tecnica":"2015-01-01","hora_inicio_eval_tecnica":1,"hora_fin_eval_tecnica":"valor","fecha_creacion_eval_tecnica":"2015-01-01 00:00:00}&callback=Ext
**************************************** UPDATE **************************************
http://192.168.100.103/ibmetrodta/yii/web/index.php/evaltecnica040801/update?records={"id_eval_tecnica":1,"fk_id_peticion":1,"area_ensayo_eval_tecnica":"valorxx","metodo_ensayo_eval_tecnica":"valorxx","lista_signatarios_eval_tecnica":"valorxx","supervision_personal_eval_tecnica":"valorxx","autorizacion_eval_tecnica":"valorxx","adecuacion_eval_tecnica":"valorxx","seguimiento_eval_tecnica":"valorxx","separacion_areas_eval_tecnica":"valorxx","control_acceso_eval_tecnica":"valorxx","orden_limpieza_eval_tecnica":"valorxx","uso_metodos_apropiados_eval_tecnica":"valorxx","confirmacion_metodos_eval_tecnica":"valorxx","instructivo_uso_eval_tecnica":"valorxx","validacion_desviaciones_eval_tecnica":"valorxx","estimacion_incertidumbre_eval_tecnica":"valorxx","verificacion_calculos_eval_tecnica":"valorxx","procedimientos_calibracion_eval_tecnica":"valorxx","trazabilidad_calibracion_eval_tecnica":"valorxx","disponibilidad_material_eval_tecnica":"valorxx","certificados_calibracion_eval_tecnica":"valorxx","plan_muestreo_eval_tecnica":"valorxx","registros_muestreo_eval_tecnica":"valorxx","tecnicas_estadisticas_eval_tecnica":"valorxx","procedimiento_muestras_eval_tecnica":"valorxx","sistema_identificacion_eval_tecnica":"valorxx","adecuacion_instalaciones_eval_tecnica":"valorxx","procedimiento_aseguramiento_eval_tecnica":"valorxx","uso_regular_material_eval_tecnica":"valorxx","participacion_intercomparaciones_eval_tecnica":"valorxx","repeticion_ensayos_eval_tecnica":"valorxx","correlacion_eval_tecnica":"valorxx","registro_aseguramiento_eval_tecnica":"valorxx","formatos_apropiados_eval_tecnica":"valorxx","cumple_requisitos_norma_eval_tecnica":"valorxx","documentacion_opiniones_eval_tecnica":"valorxx","seguridad_transmision_eval_tecnica":"valorxx","confidencialidad_eval_tecnica":"valorxx","criterios_insertidumbre_eval_tecnica":"valorxx","criterios_trazabilidad_eval_tecnica":"valorxx","numero_requisito_eval_tecnica":"valorxx","comentario_requisito_eval_tecnica":"valorxx","conclusion_eval_tecnica":"valorxx","fecha_inicio_eval_tecnica":"2015-01-01","fecha_fin_eval_tecnica":"2015-01-01","hora_inicio_eval_tecnica":1,"hora_fin_eval_tecnica":"valorxx","fecha_creacion_eval_tecnica":"2015-01-01 00:00:00"}&callback=Ext
**************************************** DELETE **************************************
http://192.168.100.103/ibmetrodta/yii/web/index.php/evaltecnica040801/delete?records={"id_eval_tecnica":1}&callback=Ext
**************************************** READ ****************************************

http://192.168.100.103/ibmetrodta/yii/web/index.php/evaltecnica040801/?start=0&limit=3&callback=Ext
**************************************************************************************
http://192.168.100.103/ibmetrodta/yii/web/index.php/evaltecnica040801/?start=0&limit=3&filter=[{"property":"id_eval_tecnica","value":1}]&callback=Ext
**************************************************************************************
http://192.168.100.103/ibmetrodta/yii/web/index.php/evaltecnica040801/?start=0&limit=3&sort=[{"property":"id_eval_tecnica","direction":"asc"}]&callback=Ext
**************************************************************************************
http://192.168.100.103/ibmetrodta/yii/web/index.php/evaltecnica040801/?start=0&limit=3&filter=[{"property":"id_eval_tecnica","value":1}]&sort=[{"property":"id_eval_tecnica","direction":"asc"}]&callback=Ext

***************************************** QUERY *********************************************
http://192.168.100.103/ibmetrodta/yii/web/index.php/evaltecnica040801/?start=0&limit=3&query=[{"id_eval_tecnica":1}]&callback=Ext

